import os
from numbers import Number
from typing import Any

import wandb


def convert_scalar(value: Any) -> float | int | None:
    """Convert Python, NumPy, or PyTorch scalar values to W&B-safe values."""
    if isinstance(value, bool):
        return int(value)

    if isinstance(value, Number):
        return float(value)

    # Handles scalar PyTorch tensors and NumPy scalar objects.
    try:
        if hasattr(value, "numel") and value.numel() == 1:
            return float(value.detach().cpu().item())

        if hasattr(value, "shape") and value.shape == ():
            return float(value.item())
    except (AttributeError, TypeError, ValueError):
        pass

    return None


def main() -> None:
    run = wandb.init(
        entity=os.getenv("WANDB_ENTITY"),
        project=os.getenv("WANDB_PROJECT", "uwmgi-segx"),
        name=os.getenv("WANDB_NAME"),
        group=os.getenv("WANDB_RUN_GROUP"),
        job_type="training",
        config={
            "slurm_job_id": os.getenv("SLURM_JOB_ID"),
            "backbone": os.getenv("SEGX_BACKBONE", "resnet34"),
            "fold": int(os.getenv("SEGX_FOLD", "0")),
            "epochs": int(os.getenv("SEGX_EPOCHS", "10")),
            "batch_size": int(os.getenv("SEGX_BATCH_SIZE", "16")),
            "learning_rate": float(os.getenv("SEGX_LR", "0.001")),
        },
    )

    # Use the SegX epoch as the x-axis for all charts.
    run.define_metric("epoch")
    run.define_metric("*", step_metric="epoch")

    # Import SegX after the W&B run is initialized.
    from segx.train.engine import SegmentationEngine

    original_log_metrics = SegmentationEngine.log_metrics

    def log_metrics_to_wandb(
        self,
        train_loss,
        val_loss,
        gt,
        preds,
    ):
        # Let SegX calculate and log everything normally.
        metrics = original_log_metrics(
            self,
            train_loss,
            val_loss,
            gt,
            preds,
        )

        payload = {
            "epoch": int(self.epoch),
            "learning_rate": float(self.lr_scheduler.lr),
            "train/loss": float(train_loss),
            "val/loss": float(val_loss),
        }

        # Add every scalar metric generated by SegX.
        # Skip preds and gt because they are large arrays.
        for key, value in metrics.items():
            if key in {"preds", "gt", "train_loss", "val_loss"}:
                continue

            scalar = convert_scalar(value)

            if scalar is not None:
                payload[f"val/{key}"] = scalar

        run.log(payload)

        print(
            "W&B logged epoch "
            f"{self.epoch}: "
            f"train_loss={train_loss:.4f}, "
            f"val_loss={val_loss:.4f}, "
            f"iou={metrics.get('iou', float('nan')):.4f}, "
            f"f1={metrics.get('f1', float('nan')):.4f}",
            flush=True,
        )

        return metrics

    # Add W&B logging without editing the private SegX repository.
    SegmentationEngine.log_metrics = log_metrics_to_wandb

    try:
        from segx.train.run import run as segx_train

        segx_train()
    finally:
        run.finish()


if __name__ == "__main__":
    main()
